export {default as Header } from './home/Header'
export {default as Deadend} from './deadend/404Page'
export {default as Login} from './authlayout/login/Login' 
export {default as Signup} from './authlayout/signup/Signup'
export {default as Product} from './product/Product'
export {default as Collections} from './collections/Collections'